# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: logging.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'logging.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rlogging.proto\"\'\n\nLogRequest\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x0b\n\x03msg\x18\x02 \x01(\t\"\x1d\n\x0bLogResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"$\n\x10MessagesResponse\x12\x10\n\x08messages\x18\x01 \x03(\t\"\x07\n\x05\x45mpty2c\n\x0eLoggingService\x12\'\n\nLogMessage\x12\x0b.LogRequest\x1a\x0c.LogResponse\x12(\n\x0bGetMessages\x12\x06.Empty\x1a\x11.MessagesResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'logging_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOGREQUEST']._serialized_start=17
  _globals['_LOGREQUEST']._serialized_end=56
  _globals['_LOGRESPONSE']._serialized_start=58
  _globals['_LOGRESPONSE']._serialized_end=87
  _globals['_MESSAGESRESPONSE']._serialized_start=89
  _globals['_MESSAGESRESPONSE']._serialized_end=125
  _globals['_EMPTY']._serialized_start=127
  _globals['_EMPTY']._serialized_end=134
  _globals['_LOGGINGSERVICE']._serialized_start=136
  _globals['_LOGGINGSERVICE']._serialized_end=235
# @@protoc_insertion_point(module_scope)
